version: '3.3'
services:
  db:
    image: mysql:9
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./my.cnf:/etc/mysql/my.cnf
      - my-db:/var/lib/mysql
volumes:
  my-db: